### ISSUE TITLE
Ban synchronization system

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#118]
https://www.civilgamers.com/community/threads/ban-syncing.5885/

Potentially something like this already exists somewhere to take over and adjust it for our case?

https://github.com/1day2die/ULX-Global-Ban-Fix

**Comment by cloakical** [comment]
Have assigned a 50 GBP bounty to this, what would be ideal is a custom system where servers have a 'group ID', and getting banned on a server with a matching group ID gets you banned on all. For this, we'll probably need to have some sort of logging in SQL.

**Comment by K2Cr** [comment]
Pending further testing and feedback.

**Comment by K2Cr** [comment]
Completed, tested and implemented
