### ISSUE TITLE
Class-Ds being able to holster guns

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#119]
Class-Ds are able to holster guns but obviously can't withdraw them, disabling them from holstering stuff would solve the issue of new players holstering guns but then being confused as to why they can't withdraw them. Or Class-Ds just accidently holstering stuff when crouched.

**Comment by Freezgam03** [comment]
Fix doesn't seem to work, you can still holster a flare gun as an example.

**Comment by CNMonarch** [comment]
If you drop a gun from a shipment, they are able to be holstered as a D-Class still.

**Comment by Kw1ll** [comment]
Tested today, you can still holster weapons and shipments that are on the ground using CTRL + E
