### ISSUE TITLE
Nanite SWEP

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#128]
Essentially a SWEP to inject a nanite into someones neck, this is to replace the unofficial brainwashing that is currently going on.

The owner of the SWEP could pull up a menu to see who they currently have a nanite injected to, and be able to detonate their nanite if the wish to do so.

This needs to also be implemented into the logs system, so staff can see who injected who at what time.

Rules also need to be put in place accordingly for it.

**Comment by cloakical** [comment]
No longer needed due to chemistry update
