### ISSUE TITLE
Create a incubation period for 008

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#132]
https://www.civilgamers.com/community/threads/008.4542/

It shouldn't be 15 minutes, but like 5 minutes where lots of stuff happens at once.

**Comment by cloakical** [comment]
not a no-access ticket

**Comment by Kw1ll** [comment]
merged with [#283](https://github.com/civilnetworks/SCP_Private_Development/issues/283)
