### ISSUE TITLE
Silence 682 roar when you are playing 682 yourself

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#136]
https://www.civilgamers.com/community/threads/682-roars-silenced-for-the-scp-player.6289/

**Comment by Kw1ll** [comment]
I dont think it should be completely silenced, just reduced how loud it is..

**Comment by Kw1ll** [comment]
Closed to reduce backlog - not necessary you can just turn down the sound on ur headphones
