### ISSUE TITLE
Make a "Elite Chef" NPC that sells high grade ingredients for Foundation

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#138]
https://www.civilgamers.com/community/threads/foundation-chef-high-grade-food.4662/

Making a "Elite Chef" NPC for Foundation get more high grade ingredients from to make better food would improve overall activity and efficiency of Chefs. 

Right now they have to switch jobs to go to surface and scavenge for it which is not really a good way to go about it.

Additionally, the elite chef NPC would maybe cost more and have a longer time to restock? And would only be available in certain kitchens?

**Comment by Kw1ll** [comment]
Closed to reduce size of backlog - Chef npcs are fine currently, no need for an "elite" one
