### ISSUE TITLE
Add a little notepad to SCP-049 to write down his "experiments"

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#142]
https://www.civilgamers.com/community/threads/scp-049-journal.4773/

**Comment by Kw1ll** [comment]
Make it so that the letters that are in the notepad for 049 are unintelligible, so when someone prints it and attempts to read it it shows as some random symbols.

**Comment by Kw1ll** [comment]
Let me emphasize that the latin stuff is NOT needed, but if a dev wants to do it they can. Otherwise just add a clipboard to kit
