### ISSUE TITLE
Clipboard improvements

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#148]
https://www.civilgamers.com/community/threads/clipboard-improvements.5233/

![Image](https://user-images.githubusercontent.com/65787083/184167977-2022463d-f3db-44b5-a32f-caeec3291392.png)

**Comment by Kw1ll** [comment]
Adding it so that you're able to copy document drafts, as well as introducing a feature such as a simple message saying "are you sure that you want to delete this" to prevent any accidental deletions.

**Comment by Kw1ll** [comment]
https://github.com/civilnetworks/SCP_Public_Development/issues/230
