### ISSUE TITLE
SCP-914 is able to give invalid models (e.g. radio model)

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#153]
https://discord.com/channels/847587034792460328/847866758266486844/1007990258849288230

https://cdn.discordapp.com/attachments/1006287902826823786/1006727250584023080/unknown.png

![Image](https://user-images.githubusercontent.com/65787083/184496594-fd6af677-d577-4f0a-b714-1e3d2e22b58b.png)

**Comment by ventz-lgtm** [comment]
Closed because no information on how to cause it
