### ISSUE TITLE
Being ragdolled by 049-2 or 008-2 and then get deployed as ERT results in having no weapons whatsoever

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#156]
https://streamable.com/6den8m

**Comment by Kw1ll** [comment]
Bug tested and appears to be working as intended, good job ventz 👍

**Comment by ventz-lgtm** [comment]
@Kw1ll You didn't change the testing state to complete

**Comment by Kw1ll** [comment]
mb, thought if I closed it after completion it wouldn't matter. cheers for heads up :)
