### ISSUE TITLE
SCP-173 delayed snapping time while contained

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#16]
Quote from Cloak:

"I don't necessarily agree with this, one idea I had was to make it so that he has an increased timer when contained (e.g. 20 seconds) and also so that the timer only starts counting down once someone is within his range."

**Comment by Kw1ll** [comment]
merged with [#283](https://github.com/civilnetworks/SCP_Private_Development/issues/283)
