### ISSUE TITLE
Making different kinds of SCP samples more worth it (e.g. Keter and Euclid or Safe) and how full the syringe is

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#164]
https://www.civilgamers.com/community/threads/make-different-scp-samples-worth-more.5994/
https://www.civilgamers.com/community/threads/syringes-research-xp-per-fullness.4502/

Additionally, it should give you more XP based on how full it is.

**Comment by Kw1ll** [comment]
This can be closed due to recent syringe/elixir changes (harder to get samples are more worth it usually)
