### ISSUE TITLE
Prevent AFK whilst in pac editor

### ISSUE THREAD

**Issue by ventz-lgtm** [civilnetworks/SCP_Public_Development#181]
Players could get kicked for being AFK while editing PAC designs.
We should prevent AFK activating while editing PAC outfits.

**Comment by Freezgam03** [comment]
Couldn't this be abused though to prevent being kicked when going AFK to eat? @ventz-lgtm

**Comment by Kw1ll** [comment]
A warning now appears when AFK, which should act as enough to stop this from happening.
