### ISSUE TITLE
When disguising with SCP-914, it doesn't give the appropriate bodygroups

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#186]

**Comment by Kw1ll** [comment]
Tested for a while, all bodygroups and models appear to be working normally and as intended. However you can sometimes become 049-2 if they are on site

**Comment by Kw1ll** [comment]
Tested for a while, all bodygroups and models appear to be working normally and as intended. However you can sometimes become 049-2 if they are on site
