### ISSUE TITLE
When disguising, it doesn't give you the appropriate bodygroups from the player you disguised as

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#187]
When disguising with the (vwar_id_card_spy) or (vwar_id_card_spy_team) and then left-click on someone to get their disguise, turn on thirdperson. Then you see that you don't have the right bodygroups (e.g. helmets or having NVGs equipped despite the original player not having them) set.

**Comment by Kw1ll** [comment]
Tested with multiple jobs, all bodygroups using disguise kits appear to be working as intended. With the same playermodel that the person you are disguising as has

**Comment by Kw1ll** [comment]
Update - after roughly 30 seconds disguised as the model, it suddenly changes to a different version. Tested with Nu-7 operative model, for first 30 seconds it worked, and then after 30 seconds some NVGs appeared equipped on my head.
