### ISSUE TITLE
Scramble HUD appears when using a computer

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#195]
![Image](https://user-images.githubusercontent.com/65787083/187083533-d283bcf4-3e97-439d-bc96-63f99fed78b8.png)

**Comment by McYeke** [comment]
HUD still persists - However is moved to the side

![Image](https://user-images.githubusercontent.com/29537551/207757053-9feda02d-8562-4828-91be-4a578770e790.png)

**Comment by McYeke** [comment]
resolved
