### ISSUE TITLE
Putting in a keypad code and then dying in the middle of it breaks your camera completely (can only be fixed by rejoining)

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#198]

**Comment by CNMonarch** [comment]
When putting in a keycode for a keypad and you get killed it will sometimes permanently break your camera, forcing you to rejoin the server.

**Comment by Kw1ll** [comment]
Attempted this, in engineer spawn and other keypad areas. Although it did nearly do it once after I force respawned instantly, the camera reset to the normal one. Bug fixed
