### ISSUE TITLE
SCP-079 scaling for hacking levels is broken

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#208]
In the clip you can see that it says Impenetrateble, which is Level 5, even though it should say Strong for 079 at all times, since his hacking scaling sets all hacking difficulties that are above level 4 to be level 4.

https://medal.tv/games/garrys-mod/clips/BCNqf6VdapxnC/d1337F789ZmK?invite=cr-MSxDcUwsMTE5NDQ1MjA5LA

**Comment by McYeke** [comment]
I misread the ticket - This is resolved
