### ISSUE TITLE
Surface Jobs can see the Containment Breach notification at the top of the screen

### ISSUE THREAD

**Issue by CheddarSniffer** [civilnetworks/SCP_Public_Development#21]
Doesn't make sense why they should be able to see it, it's not like the foundation would broadcast a breach all around the surface

**Comment by cloakical** [comment]
adding flag `SurfaceJob` to a job in vjobeditor on the dev server should now stop it from hearing / seeing breach announcements at the top of the screen, someone please test

**Comment by McYeke** [comment]
Resolved with surfacejob flag - no issues reported since
