### ISSUE TITLE
Certain jobs getting turned into an error model when being converted by 049

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#210]
So far only the Combat Medic is affected, when someone as it gets infected by 049 and becomes a zombie, they get turned into a invalid model. Most likely due to the model path changes.

![Image](https://user-images.githubusercontent.com/65787083/191956580-113c97d0-0d1f-4d6a-940d-4e5cbd075fb8.png)

**Comment by McYeke** [comment]
resolved
