### ISSUE TITLE
Bodygroups getting set back to default after sometime after applying disguise

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#212]
This seems like the same issue that we had with SCP-035 when it had a host who was a containment specialist, that it goes from the correct skin back to the default skin after sometime.

Sometimes it's instantly after disguising, sometimes it takes a while.

https://user-images.githubusercontent.com/65787083/192141481-afbc8e67-1390-4c22-b2a6-e99b643b2025.mp4

https://user-images.githubusercontent.com/65787083/192141495-b1472404-dd0b-417f-ad8c-3a24a41ac271.mp4

**Comment by K2Cr** [comment]
This was caused by the hunger module
