### ISSUE TITLE
SCIPNET - Allow documents to be uploaded 1 clearance higher than own

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#217]
Accepted Suggestion: https://www.civilgamers.com/community/threads/scipnet-document-celarance-fix.7469/

Allow documents to be uploaded to SCIPNET that is one clearance higher than own.

**Comment by Kw1ll** [comment]
Closed to reduce backlog - merged with https://github.com/civilnetworks/SCP_Public_Development/issues/87
