### ISSUE TITLE
Female suited playermodels

### ISSUE THREAD

**Issue by ventz-lgtm** [civilnetworks/SCP_Public_Development#221]
3 Female models should be converted to playermodels from the following addon: https://steamcommunity.com/sharedfiles/filedetails/?id=2718398707&searchtext=female+suit

Each model needs the multiple female heads plus the original head of the model as bodygroups and need to be rigged as playermodels.

**Comment by ventz-lgtm** [comment]
Added bounty of 50 GBP

**Comment by cloakical** [comment]
Currently we have no modellers, so I've removed the bounty from this ticket for now.
