### ISSUE TITLE
vComputers CI - SCIPNET expansion

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#229]
Ci are requesting;
New File Path in the CI SCINET, this one would be Medical, and would have the following paths...
/CHAOS/Medical
/CHAOS/Medical/Evaluations
/CHAOS/Medical/Field Reports
/CHAOS/Medical/Medical Logs

https://www.civilgamers.com/community/threads/addition-to-ci-scinet.8051/

**Comment by 0-Marco** [comment]
- [ ] /CHAOS/Medical
- [ ] /CHAOS\Medical/Evaluations
- [ ] /CHAOS/Medical/Field Reports
- [ ] /CHAOS/Medical/Medical Logs

**Comment by 0-Marco** [comment]
For future reference, this can be done by any Super Admin in-game.
