### ISSUE TITLE
vComputers - GOC Document Format

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#230]
GOC are requesting a document format for their clipboards and uploading of documents

https://www.civilgamers.com/community/threads/add-a-goc-clipboard-template.8101/

**Comment by KaptianCore** [comment]
could give them 2 or more templates:
- R&D Report Template
- Standard GOC Template (a clone of the foundation one)
- UN Document Template (stuff that can be given out to public such as press releases etc)

these are just a few ideas could also have investigation templates and stuff

**Comment by Kw1ll** [comment]
Merged with https://github.com/civilnetworks/SCP_Public_Development/issues/148
