### ISSUE TITLE
Surface Spawn - Remove jobs with the exception of Nu-7 / Beta-1 from surface spawn

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#231]
https://www.civilgamers.com/community/threads/remove-the-ability-for-some-jobs-to-spawn-in-the-facility-gate.8049/

**Comment by Kw1ll** [comment]
I think this is FTP+, so I am moving it over there

**Comment by IlFlames** [comment]
Resolved.
