### ISSUE TITLE
SCP - Expand the "info box" on SCP spawn to include abilities

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#232]
Expand the boxes when a SCP spawns with their abilities, passive and active effects of SCPs and create a command to make the menu be able to be brought up such as !scpmenu

https://www.civilgamers.com/community/threads/add-scp-abilities-info-to-the-f4-menu.8135/

**Comment by Kw1ll** [comment]
Merged with [#283](https://github.com/civilnetworks/SCP_Private_Development/issues/283)
