### ISSUE TITLE
SCP-035 Improve interaction of mask

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#239]
https://www.civilgamers.com/community/threads/scp-035-interaction.8355/

Content Note:

Either increase hitbox of mask to make it easier to put on or auto put on the mask if the subject reaches the containment box and it is open, as this is where the influence would be at its strongest

**Comment by McYeke** [comment]
Appended high due to interaction with SCP gameplay loop

**Comment by Kw1ll** [comment]
Merged with [#283](https://github.com/civilnetworks/SCP_Private_Development/issues/283)
