### ISSUE TITLE
SCP-096 - Multiple Photo spawns

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#241]
In order to give SCP-096 a better chance at breaches we have decided to accept the counter suggestion from SinisterPig

"remove the cap on 096 photos, if one despawns or is stuck somewhere there shouldn’t be a hard cap on how many there can be since they are usually instantly destroyed."

Suggestion: https://www.civilgamers.com/community/threads/scp-096-picture-whereabouts.8373/post-51964

**Comment by Kw1ll** [comment]
Merged with https://github.com/civilnetworks/SCP_Private_Development/issues/226
