### ISSUE TITLE
Perma Guns - Make a menu to enable what jobs you wish to add perma guns for and which ones you don't

### ISSUE THREAD

**Issue by Kw1ll** [civilnetworks/SCP_Public_Development#242]
Perma Guns need a UI menu where you can select which jobs you wish for the perma gun to spawn on for. Along with this however, it will only be applicable to the combat jobs listed;

MTF
GENSEC
Intel
CI
GOC
Combat Medic
SA/SD
IA
Dpt. Directors
Containment Specialist
Ranger
MC&D
Gun Dealer & Heavy Gun Dealer

**Comment by KaptianCore** [comment]
Better Idea would just to have a vjobeditor property called `getsPermaWeapons` then just adding a check if they don't have that property they won't spawn with it.

 A menu seems excessive.

**Comment by Kw1ll** [comment]
Ventz has denied this, was informed afterwards via yeke hence closing this thread
