### ISSUE TITLE
8854 Nerfs

### ISSUE THREAD

**Issue by Kw1ll** [civilnetworks/SCP_Public_Development#250]
8854 has been far too strong in the current meta, making surface players ignore him or straight up leave so they do not have to deal with it.

Content Team has agreed on some nerfs;

- SCP 8854 Should have reduced attack speed. His current attack speed is the highest in the game allowing him to spam click until a successful hit, this should not be the case and should be reduced to either 3 hits or 2 hits a second, hopefully punishing players who spam click.

- SCP 8854 Should have reduced attack range, 8854 can currently hit people ontop of certain buildings, this should be reduced to allow counterplay

- SCP 8854 Should have sound, for a surface SCP having no sound just makes him a ninja, especially at this speed. SCP 8854 should make some kind of rattling sound or another sound that can be heard from far away, to make him less sneaky

**Comment by McYeke** [comment]
Resolved by cloak 10/11/22
