### ISSUE TITLE
SCP-9000-A-3 - Ability to break heavy doors

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#251]
SCP-9000-A-3 as a strong SCP should have the ability to break stronger bulkhead doors, see suggestions below;

https://www.civilgamers.com/community/threads/give-the-blind-9000-the-ability-to-break-bulkheads.8722/#post-54259
https://www.civilgamers.com/community/threads/scp-9000-a-3-improvement.3916/

**Comment by Kw1ll** [comment]
Merged with https://github.com/civilnetworks/SCP_Private_Development/issues/208
