### ISSUE TITLE
Add no 106-tp zones to spawn locations

### ISSUE THREAD

**Issue by Kw1ll** [civilnetworks/SCP_Public_Development#256]
Add 106 no tp zones into spawn locations just as we did to his dimension.

**Comment by 0-Marco** [comment]
Will do this later today.

- [ ] Ethics Committee Office
- [ ] O5 Office
- [ ] A-1 Bunks
- [ ] O-1 Bunks
- [ ] E-11 Bunks
- [ ] Nu-7 Bunks
- [ ] B-1 Bunks
- [ ] Site Affairs spawns

Obviously, there are more spawns, but these are the only ones I will be doing it to.
