### ISSUE TITLE
Make it so field kits/first aid kits can heal up to spawn HP

### ISSUE THREAD

**Issue by Kw1ll** [civilnetworks/SCP_Public_Development#260]
Currently, the only way D-class Scout/Brute can heal to full hp again is through SCP-500 or health packs, we believe it would increase medical RP and make more sense if we could heal these classes up to full HP with field kits/first aid kits

**Comment by Tarquin-Cassius** [comment]
Works on Dev Server (20/11/2022)

**Comment by Kw1ll** [comment]
Works on main, closing as completed
