### ISSUE TITLE
SCP-7722 Ammo does not replenish when recontained

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#262]
**Description**
Whenever SCP-7722 is breached from containment, after continued crossbow use, when re-contained he does not receive any ammo back

**Steps to Reproduce**
1. Become 7722
2. Get RC'd as 7722

**Expected Behaviour**
Refund all the ammo back to 7722 

**Actual Behaviour**
Upon being RC'd you still do not get refunded back your ammo, and have an even more limited amount of ammo after breach.

**Comment by cloakical** [comment]
On dev server after restart, spawning/breaching as 7722 sets your ammo to 200 crossbow bolts exactly

**Comment by Kw1ll** [comment]
Works on dev, testing complete
