### ISSUE TITLE
D-Class Scout - Head is not attached to torso

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#264]
On the D-Class scout, the head is not attached to the torso properly.

![image](https://user-images.githubusercontent.com/29537551/207380661-abb4f5e4-e439-4198-9358-40b11adac469.png)

**Comment by McYeke** [comment]
Unable to replicate this tearing, been attempting with Jericho for a good while and could not replicate this level of tearing

**Comment by cloakical** [comment]
Updated, on live server after restart
