### ISSUE TITLE
SCPs - When door is left open for 30m, breach occurs

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#270]
https://www.civilgamers.com/community/threads/scps-additional-breach-method.9780/

Feature Specification: 

In order to give E-11 patrol routes and things to do other than just stand at a checkpoint, the consequences are real for negligence of leaving a SCP CC door open, if a SCP CC door is left open for 30 minutes, the SCP will then breach (However if a breach is active, this timer will halt)

In order to prevent mass abuse, this will be prevented at 65 players and no SCPs can breach in this method.

**Comment by Kw1ll** [comment]
Merged with [#283](https://github.com/civilnetworks/SCP_Private_Development/issues/283)
