### ISSUE TITLE
SCP-096 - Reduce view effects (screen shake / saturation)

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#274]
https://www.civilgamers.com/community/threads/multiple-scp-096-changes-suggestion.9808/

Feature Specification: Reducing the screen effects of SCP-096 to create a more pleasant experience for users playing as SCP-096, by returning the view a bit more to normalcy, this will require experimentation.

**Comment by Kw1ll** [comment]
merged with #283
