### ISSUE TITLE
Vcraft - Filled chemical containers lose items on AFK / World de-loading

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#276]
Bug description:

If a player goes AFK with a chemical in their hand or on the floor and they are the only person in the area and it de-loads the vials will render back in empty and the vials will have no liquid inside, this is causing a major issue for players.

Reproduction:
1. Hold chemical in hand
2. Go AFK
3. Move around once AFK and vial is empty

**Comment by Kw1ll** [comment]
https://medal.tv/games/garrys-mod/clips/O81pozvel_EEe/d1337quxJo8f?invite=cr-MSxDMmQsNzQ2NzE0NTEs
https://medal.tv/games/garrys-mod/clips/O857l6ETnoS3B/d1337qN3clPi?invite=cr-MSxFNWIsNzQ2NzE0NTEs

clips of both, seems that it disappears whilst in hand but not on floor

**Comment by ventz-lgtm** [comment]
Bro its on the test server not live

**Comment by Kw1ll** [comment]
mfw

**Comment by Kw1ll** [comment]
https://medal.tv/games/garrys-mod/clips/O8yvbU7-zZRIW/d1337eHAdOlH?invite=cr-MSxZZkosNzQ2NzE0NTEs

seemingly fixed
