### ISSUE TITLE
SCP-912 - Able to get fractures

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#278]
SCP-912 is able to get a fracture hindering movement, this apparently occurs during fall damage in/on an elevator.
![image](https://user-images.githubusercontent.com/29537551/208271050-892ddf3c-615a-46db-a271-fa9af46086d2.png)

**Comment by cloakical** [comment]
Fix is on dev server after restart, prevents all SCPs getting fractures

**Comment by Kw1ll** [comment]
Works as intended
