### ISSUE TITLE
Add draw-back to using SCP-914 on Very Fine

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#28]
Quote from Cloak:

"This would be something like perhaps a 50% chance that the weapon can explode when you use it, dealing 100 damage to the player"

**Comment by Kw1ll** [comment]
Closed to reduce backlog - does not seem necessary considering how rarely 914 is used anyways, could look into doing it if we decide on a 914 mini rework in future
