### ISSUE TITLE
VComputer QOL changes

### ISSUE THREAD

**Issue by MistJules** [civilnetworks/SCP_Public_Development#289]
Suggestion: https://www.civilgamers.com/community/threads/vcomputer-addition-suggestion.10000/

This would add a feature to be able to download/transfer drafts from SCRIPNET so you can have an editable version of documents from SCRIPNET in your clipboard.

Or another option could be to add an "editable" box like the signatures one where you could print off a template for people and they would still be capable of writing in that box.

**Comment by MistJules** [comment]
Suggestion: https://www.civilgamers.com/community/threads/documents-allignment.9947/

This would add an alinement feature that would make formatting documents easier on players.

This would allow them to align text to the left, right, or center of the document.

**Comment by Kw1ll** [comment]
Merged with [#282](https://github.com/civilnetworks/SCP_Private_Development/issues/282)
