### ISSUE TITLE
Make SCP-073 easier to beam

### ISSUE THREAD

**Issue by MistJules** [civilnetworks/SCP_Public_Development#290]
Suggestion: https://www.civilgamers.com/community/threads/make-scp-073-easier-to-beam.10053/

This would make 073 easier to beam as 073 player tend to stand in the way of breaches or do not listen to orders.

One of the ideas was to make it like 2295 or 999 and just beamable with one beam and taking about 5/10 seconds to RC him.

**Comment by Kw1ll** [comment]
merged with #283 and closed
