### ISSUE TITLE
SA/SC Force ERT Call

### ISSUE THREAD

**Issue by MistJules** [civilnetworks/SCP_Public_Development#291]
Suggestion: https://www.civilgamers.com/community/threads/sa-sc-force-ert-call.10111/

SA/SC will be able to call ERT if certain criteria are met (i.e breach has been going on for x+ mins, x number of SCPs are breached, etc.) Of course, I understand this can be abused, but if it is locked behind criteria as mentioned above as well as a rule potentially implemented to reduce abuse of the ERT call I feel as this will not be an issue. This could be placed in EoC which currently has no real use.

**Comment by Kw1ll** [comment]
Closed - Exec team has decided to keep current system in favor over this one
