### ISSUE TITLE
Renaming CGITV to Parawatch

### ISSUE THREAD

**Issue by MistJules** [civilnetworks/SCP_Public_Development#295]
Suggestion: https://www.civilgamers.com/community/threads/rename-cgitv-to-parawatch.10028/

This will rename CGITV to Parawatch which is a in lore news and online conspiracy-based group who know of the Foundation but know nothing about it.

Lore: https://scp-wiki.wikidot.com/parawatch-hub

**Comment by McYeke** [comment]
Resolved by @IlFlames
