### ISSUE TITLE
VComputers - Breifcases lose documents if weapon stripped or returning from AFK

### ISSUE THREAD

**Issue by McYeke** [civilnetworks/SCP_Public_Development#299]
Description:

Users have reported that when using the Breifcase or Satchel, if these are stripped or removed from the culling whilst AFK, on return the documents inside will be removed, leaving you with an empty breifcase/satchel

Replication steps (Weapon strip)
1. Hold a Briefcase / Satchel with documents inside
2. Have the briefcase removed by weapon checker
3. Have briefcase returned by pressing "R"
4. Look inside and no docs

Replication steps (AFK)
1.  1. Hold a Briefcase / Satchel with documents inside
2. Go AFK until weapons are culled
3. Return from "AFK"
4. Documents are now missing

**Comment by cloakical** [comment]
fix is on dev server after restart

**Comment by Lufttt** [comment]
Not sure if dev server has already restarted, but just tested this and the same issue occurs.

**Comment by cloakical** [comment]
fixed again

**Comment by Lufttt** [comment]
After being fixed again, this works perfectly fine. Will mark as closed with comment now.
