### ISSUE TITLE
AFK check 10 minutes before a SCP breaches

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#30]
Quote from Cloak:

"At the 10 minute mark before an SCP breaches, check if they are AFK. If they are, place an AFK warning on their screen, then wait 5 minutes. If they do not return within that timeframe, remove them from the SCP job"

**Comment by Kw1ll** [comment]
merged with https://github.com/civilnetworks/SCP_Public_Development/issues/296
