### ISSUE TITLE
Allow D-block phones to call D-block Kitchen

### ISSUE THREAD

**Issue by LilyValen** [civilnetworks/SCP_Public_Development#320]
Description: Suggestion Accepted: Allow D-block phones to call D-block Kitchen

https://www.civilgamers.com/community/threads/allow-d-block-phones-to-call-d-block-kitchen.10519/

**Comment by McYeke** [comment]
Completed: Added D-Block phones to "kitchen" restricted to tag and added kitchen phone with the "kitchen" tag.
