### ISSUE TITLE
Selectable Voice Chat ranges

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#33]
https://www.civilgamers.com/community/threads/voice-chat-ranges.3833/

**Comment by Kw1ll** [comment]
Would be best to disable the "Shout" option for jobs like D-class, as it would just cause nuisances all around really.

**Comment by Kw1ll** [comment]
Would be best to disable the "Shout" option for jobs like D-class, as it would just cause nuisances all around really.
