### ISSUE TITLE
Merge noclip, cloak and god into one command

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#37]
https://www.civilgamers.com/community/threads/staff-suggestion-noclip-cloak.3911/#post-25266

**Comment by KaptianCore** [comment]
Toggleable command (so it can be binded)

- Cloaks / Uncloaks
- Noclips / Unnoclips
- Gods / Ungods

Add an isAdministrate function (this will then be added to the 096 ignore, it checks if they are in the "admin" mode and it will ignore them.)

**Comment by KaptianCore** [comment]
Finished this and sent to cloak unsure if I move this to the testing area ?

**Comment by KaptianCore** [comment]
cloak said he will upload this to the scp dev server.

**Comment by cloakical** [comment]
moved back to in progress as it needs more work

**Comment by cloakical** [comment]
on live server, can be moved to complete tomorrow if no problems flagged up by staff

**Comment by KaptianCore** [comment]
Went live 3 days ago and no issues reported to me or to content team (as far as I have seen)
