### ISSUE TITLE
SCP-049-2 Buffs

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#38]
https://www.civilgamers.com/community/threads/misc-abilities-scps.3923/

Make it so 049-2s have a speed / damage / hp buff when close to 049, but don't add a debuff when they're far away from 049-2 as it's suggested, because it takes 049-2 around 10 seconds to turn and by then 049 can be on the other side of the facility

**Comment by Kw1ll** [comment]
Deleted after reviewing with Senior SL and other content team. Came to the decision that this change was heavily unnecessary

**Comment by McYeke** [comment]
No idea why this was left open if it has been denied by SL.
