### ISSUE TITLE
Give SCP-682 a new ability

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#39]
https://www.civilgamers.com/community/threads/scp-682-buff-new-ability.3867/#post-25008
https://www.civilgamers.com/community/threads/give-682-a-stunning-ability.4235/

Maybe instead of this a new ability can be introduced to 682. Where he can roar and stun everyone around him, essentially giving them the tranquilized effect but stronger, with heavier distortion, screenshake and being unable to jump/crouch/run, aswell as damage them by like 5-10hp.

**Comment by McYeke** [comment]
complete
