### ISSUE TITLE
SCP-173 changes

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#42]
https://www.civilgamers.com/community/threads/misc-abilities-scps.3923/

**Comment by Kw1ll** [comment]
SCP 173 whilst being looked at can move his camera, without moving his model. Whilst doing this, he gets to look at and Select who to teleport to to snap their neck

**Comment by Kw1ll** [comment]
Closed and merged with [#283](https://github.com/civilnetworks/SCP_Private_Development/issues/283)
