### ISSUE TITLE
Add object SCPs in CI base

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#45]
https://www.civilgamers.com/community/threads/suggestion-add-scp-010-to-ci.3850/

**Comment by KaptianCore** [comment]
Why is this here @Freezgam03 (I was just looking around at the dev tracker) the suggestion was denied?

**Comment by Kw1ll** [comment]
Closed for the time being as not planned due to conflicting suggestions/plans, can revisit later
