### ISSUE TITLE
Command to credit SCPs after testing

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#57]
I guess the way this can be done is to make a command like "!creditscp" and it just gets the researcher position and it checks which SCP chamber he is currently in?

**Comment by CoolfraeCN** [comment]
Due to this being highly abusable it would be better for scp's to get more kill xp etc when not breached. - Content team backlog meeting

**Comment by McYeke** [comment]
https://www.civilgamers.com/community/threads/scp-crediting.8389/#post-52115

**Comment by Kw1ll** [comment]
closed and added to https://github.com/civilnetworks/SCP_Public_Development/issues/235
