### ISSUE TITLE
Benefits for Class-Ds escaping to surface

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#61]
https://www.civilgamers.com/community/threads/suggestion-benefits-for-escape.3844/

**Comment by cloakical** [comment]
Feature Specification:
- Add a convar which can be modified to set the 'surface height'. Passing this surface height means you've 'escaped'
- Escaping as D-Class jobs or SCPs gives you the option to press a button to respawn (just killing them will suffice - this will also end SCP's breaches), which will give you a large chunk of XP/Money as a reward.
- D-Class check: `VWAR.SCP:IsClassD(ply)`
- SCP check: `VWAR.SCP:IsSCP(ply)`
- To avoid errors when developing without VWAR installed you can add `VWAR and` to the start of these checks, e.g. `VWAR and VWAR.SCP:IsSCP(ply)`
- When someone escapes and presses the button, print something like `ply:Nick() has successfully escaped the facility and claimed their rewards!` and place a cooldown until they can next receive an escape reward.

**Comment by cloakical** [comment]
moved back to in progress as it needs more work

**Comment by KaptianCore** [comment]
Finally done, tested by Yeke and should be good for the live server whenever one of the epic peeps get time

**Comment by McYeke** [comment]
Added in recent update.
