### ISSUE TITLE
More XP for syringes

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#68]
20% - 20 XP
40% - 40 XP
60% - 60 XP
80% - 80 XP
100% - 100 XP

Can certainly be de-buffed as that is slightly OP but that is the idea.

**Comment by Freezgam03** [comment]
Made this Programming, as I am not sure if the Syringes already have a config file for the XP rewards.

**Comment by Kw1ll** [comment]
@McYeke possible close

**Comment by McYeke** [comment]
Closed as per latest update
