### ISSUE TITLE
IA Clothing Changes

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#76]
https://www.civilgamers.com/community/threads/ia-clothing-change-for-ambassadors.4231/

**Comment by Kw1ll** [comment]
@CheddarSniffer whats happened on this

**Comment by Kw1ll** [comment]
https://www.civilgamers.com/community/threads/internal-affairs-ambassadors-model-change.8371/

they want a white coloured shirt

**Comment by McYeke** [comment]
Set ambassadors model to 
models/player/suits/male_01_open.mdl
models/player/suits/male_02_open.mdl
models/player/suits/male_03_open.mdl
models/player/suits/male_04_open.mdl
models/player/suits/male_05_open.mdl
models/player/suits/male_06_open.mdl
models/player/suits/male_07_open.mdl
models/player/suits/male_08_open.mdl
models/player/suits/male_09_open.mdl

Set skin to : 1
