### ISSUE TITLE
Give AODs SCP Light

### ISSUE THREAD

**Issue by Nilskatten** [civilnetworks/SCP_Public_Development#85]
[**What does this suggestion change/add/remove:**
Give's AOD's the ability to see when lights are off. One fix that I find fit is SCP light. NVG's aren't really optimal since you can't see well with them either.

**Possible Positives of the suggestion (At least 2):**
Makes our time as AOD a lot easier.

**Possible Negatives of the suggestion:**
None

**Based on the Positives & Negatives, why should this suggestion be accepted:**
As mentioned earlier. Makes being AOD much easier I'm sure staff can back me up on this one](https://www.civilgamers.com/community/threads/staff-suggestion-about-aods.3982/)

**Comment by cloakical** [comment]
This is a programming change, not configuration, but quick to do
