### ISSUE TITLE
Tranquilizer Stun Baton

### ISSUE THREAD

**Issue by Freezgam03** [civilnetworks/SCP_Public_Development#99]
Currently, Security have no real way of stopping people, specifically Class-Ds from running away without either shooting them to try and put them under FearRP if they care that much. Giving them a Stun Baton that applies the tranquilizing effect, that is a bit more dumbed down but still fulfills it's job of stopping someone dead in their tracks. Like it should just greatly reduce someones speed and make them unable to jump or crouch, maybe a bit of blurred vision as well, but not as heavily as when getting shot by a tranq gun.

Additionally I think this Stun Baton should give a "slight" speed buff when held, not too noticeable but it should be there so anyone can catch up to people who are running away.

This could greatly impact of how many Class-Ds are actually killed when running out of D-Block, if enough people have the Stun Baton and are able to utilise it, obviously would need some restrictions like that it should have a 2-5 second cooldown after being used, and obviously not be able to be used on SCPs.

**Comment by McYeke** [comment]
stunstick already apart of gensec kit
